### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by WilliamsJack** [SFXRescue/SARTInterface#15]
Easy on the eyes.

At some point it might be a good idea to store user preferences in cookies (per-control panel preferences) or in a/the robot config (per robot preferences).

- [x] Add CSS classes for all elements that can change theme
- [x] CSS file per theme
- [x] Dynamically load theme CSS files

```
"Needs more dark theme"
    ~ Aaron Maggs, 2019
```
```
"Dark theme!"
    ~ Connor Kneebone, 2019
```
```
"IT HAS DARK THEME AND I LOVE DARK THEMES"
    ~ Aaron Maggs, 2019
```
```
"Dark theme 😍"
    ~ Aaron Maggs, 2019
```
```
"Dark mode all the things"
    ~ Aaron Maggs, 2019
```

**Comment by Conr86** [comment]
The [official method](https://getbootstrap.com/docs/4.3/getting-started/theming/) for implementing themes in Bootstrap is... a little tricky. It looks pretty powerful and neat, but it seems to rely heavily on using Node.js or at the very least, using Sass and it's build system. I'd naturally prefer to use this method if it's viable, but it will take a bit of work at least.
